[project]
name = "isoplots"
version = "0.3.10"
description = "Plot Utilities for ISOFIT"
readme = "README.rst"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["isofit", "isofit-plots"]
authors = [
  {name = "James Montgomery", email = "J.Montgomery@jpl.nasa.gov"}
]
maintainers = [
  {name = "James Montgomery", email = "J.Montgomery@jpl.nasa.gov"},
  {name = "Philip Brodrick", email = "philip.brodrick@jpl.nasa.gov"}
]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "click",
  "kaleido",
  "matplotlib",
  "nicegui<3",
  "plotext",
  "rioxarray",
  "spectral",
  "plotly",
  "xarray",
  "selenium-screenshot>=3.0.0",
]

[project.urls]
repository = "http://github.com/isofit/isofit-plots"

[project.scripts]
isoplots = "isoplots:__main__.cli"

[project.entry-points."xarray.backends"]
envi = "isoplots.isonice.utils.wd:EnviBackendEntrypoint"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["isoplots/**"]

[tool.hatch.build.targets.wheel]
packages = ["isoplots"]
